#!/usr/bin/env python

import sys
import pwd
import os

USER = pwd.getpwuid(os.getuid()).pw_name
FAKE_CLIPBOARD = '/tmp/clipmenu-fake-clipboard.' + USER


def write_to_fake_clipboard(text):
    with open(fake_clipboard, 'w+') as clip_f:
        clip_f.write(text)


def read_from_fake_clipboard():
    with open(fake_clipboard, 'r') as clip_f:
        return clip_f.read()


def main(argv):
    if '-i' in argv:
        write_to_fake_clipboard(sys.stdin.read())
    else:
        sys.stdout.write(read_from_fake_clipboard())


if __name__ == '__main__':
    main(argv=sys.argv[1:])
